config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
  	resources :comments do
  		resources :commentlike
  	end
  	resources :gossiplike, only: [:create, :destroy]
  end
  resources :contact, only: [:index]
  resources :team, only: [:index]
  resources :user, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get '/',to: 'static#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates :name, length: { minimum: 2 }
  validates :name, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord

 belongs_to :gossip, optional: true
 belongs_to :user
 validates :user_id, presence: true	
 validates :gossip_id, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  has_many :likes
  validates :title, presence: true, length: { in: 3..140 }
  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
	belongs_to :user
	validate :unique_like
                # cette methode 
			def unique_like
		if User.find(user_id).has(gossip_id)&&User.find(user_id).has(comment_id)
			errors.add(:gossip_id,:comment_id, message: "déjà fait") 
		end

	end

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
	has_many :recipient_lists
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
    belongs_to :private_message
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tags
	has_many :gossips, through: :gossip_tags
	validates :title, length: { minimum: 2 }

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  validates :email,
  uniqueness: true,
  presence: true,
  uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 2 }

  validates :password, presence: true, length: { minimum: 6 }

    def has(gsp_id)
    
    self.likes.map{|like| like.gossip_id}.include?(gsp_id)
    
  end

      def hasc(cm_id)
    
    self.likes.map{|like| like.comment_id}.include?(cm_id)
    
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:index,:new,:create]
  layout "application", except: [:new, :create]

  def index

  end

  def show
    if params[:id].to_i <=0
      redirect_to "/gossips"
    end

  end

  def new
    @gossip = Gossip.new()
  end

  def create
    @gossip = Gossip.new('user_id' => current_user.id,'title' => params[:title],'content' => params[:content])

    if @gossip.save
      params[:tag].try(:each) do |i|
        @gossiptag = GossipTag.new('tag_id' => Tag.all.find(i).id,'gossip_id' => @gossip.id)
        @gossiptag.save
      end
      flash[:succes] = "Gossip crée avec succes"
      redirect_to "/gossips"
    else  
      render 'new'
    end
  end


  def edit
    @gossip = Gossip.new()
  end

  def update
      # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params
      # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)

      @gossip = Gossip.find(id = params[:id].to_i)

      if @gossip.user_id == current_user.id
        if @gossip.update('user_id' => current_user.id,'title' => params[:title],'content' => params[:content])
          Gossip.order('id ASC')
          flash[:edit] = "Gossip modifié avec succes"
          redirect_to "/gossips"
        else
          render :edit
        end
      end
    end

    def destroy
      # Méthode qui récupère le potin concerné et le détruit en base
      @gossip = Gossip.find(id = params[:id].to_i)

      puts @gossip.user_id 
      puts current_user.id

      if @gossip.user_id == current_user.id

        @gossip.destroy
        flash[:delete] = "Gossip supprimé avec succes."
        redirect_to "/gossips"
        @@num2="1"
      else
        redirect_to "/gossips"
      end


    end


    private
    def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
   end

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/commentlike_helper.rb
module CommentlikeHelper
    def nb_comment_likes?(id)
    CommentLike.where(comment_id: id).count
  end
  def is_comment_liked?(comment_id)
    CommentLike.where(comment_id: comment_id, user: current_user).count > 0
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossiplike_helper.rb
module GossiplikeHelper
    def nb_gossip_likes?(id)
    GossipLike.where(gossip_id: id).count
  end
  def is_gossip_liked?(gossip_id)
    GossipLike.where(gossip_id: gossip_id, user: current_user).count > 0
  end
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].nil?
    return true
  end

  def is_owner?(id)
    return false if current_user.nil?
    return true if current_user.id == id
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gossips/edit.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh">

  <div class="container-flex w-100 m-0 p-0">

   <% if @gossip.errors.any? %>
   <div class="row justify-content-center m-0 p-0">
    <div class="col-11 col-sm-11 col-lg-8 text-center shadow bg-light rounded p-0">

     <div class="alert alert-danger m-0" role="alert">
      <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% end %>

    <div class="row justify-content-center m-0 p-0">

      <div class="col-11 col-sm-11 col-lg-8 text-center shadow-sm bg-light rounded pb-4 pt-2">
        <h2 class="h1-responsive font-weight-bold text-center my-4">Gossip</h2>
        <p class="text-center w-responsive mx-auto mb-5">Voici la séction gossip :</p>
        <div class="row p-0 m-0">
          <div class="row p-0 m-0">
            <div class="col-md-12">
              <div class="md-form mb-0">

              </div>
            </div>
          </div>
          <div class="col-md-12 text-center">
            <ul class="list-unstyled mb-0">
              <li><%= form_tag url_for(action: 'update'), method: "patch" do %>

                <div class="row justify-content-center p-0 m-0">
                  <div class="col-4">
                    <div class="input-group mb-3">
                      <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Nouveau titre</span>
                      </div>
                      <input type="text" name="title" id="title" class="form-control" placeholder="Titre" aria-label="Titre" aria-describedby="basic-addon1">
                    </div>
                  </div>
                </div>
                <div class="row justify-content-center p-0 m-0">
                  <div class="col-4">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">Nouveau contenue</span>
                      </div>
                      <textarea name="content" id="content" class="form-control" aria-label="With textarea"></textarea>
                    </div>
                  </div>
                </div>
                <div class="mt-3">
                </div>
                <button type="submit" name="commit" class="btn btn-primary rounded-0">Submit</button>

                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/gossips/index.html.erb
<div class="container-fluid" style="margin-top: 130px">


  <div class="row justify-content-center mt-5">


  <div class="col-xl-6 offset-xl-1" >

    <% if flash[:succes] %>

     <div class="alert alert-success mb-4 m-0" role="alert">
      <div><%= flash[:succes] %></div>

  </div>
  <% end %>
      <% if flash[:edit] %>

     <div class="alert alert-success mb-4 m-0" role="alert">
      <div><%= flash[:edit] %></div>

  </div>
  <% end %>
      <% if flash[:delete] %>

     <div class="alert alert-info mb-4 m-0" role="alert">
      <div><%= flash[:delete] %></div>

  </div>
  <% end %>
    <%Gossip.all.order("created_at DESC").each do |nb|%>
    <div class="row shadow-sm bg-white justify-content-between rounded-sm pb-3 pt-3 pl-3 mb-3 text-dark border pr-0 m-0">
     <div class="col border-right">

      <span class="font-italic mogos">
       <a class="spec" href="user/<%=nb.user.id%>"> <%=nb.user.first_name%> <%=nb.user.last_name%></a> 
     </span>
     <br>
     <a href="/gossips/<%=nb.id%>" class="link">
      <%=nb.title%> 
      <br>
      <span class="text-black-50"><%=nb.content%> <span>
      </a>
    </div>
    <div class="col-auto d-flex justify-content-center align-items-center text-black-50 m-0 p-0">
      <%if current_user.has(nb.id)%>       
      <%= form_tag gossip_gossiplike_path(nb.id,Like.where(:gossip_id =>nb.id,:user_id => current_user.id).first.id
      ), method: "delete" do %>
      <button type="submit" name="buto" value="yes" id="fontaws" class="fas fa-heart fa-2x spec ml-3 mr-3"></button>
      <%end%>
      <%else%>
      <%= form_tag gossip_gossiplike_index_path(nb.id), method: "post" do %>
      <button type="submit" name="buto" value="yes" id="fontaws" class="far fa-heart fa-2x spec ml-3 mr-3"></button>
      <%end%>
      <%end%>
      <%if current_user == nb.user%>
      <%= form_tag gossip_path(nb), method: "delete" do %>
      <button  type="submit" id="fontaws" name="<%=nb%>" class="fas fa-times fa-2x spec mr-3"></button>
      <%end%>
      <%end%>
    </div>
  </div>
  <%i=0%>
  <%end%>
</div>
<div class="col-auto center-block text-center">
  <div class="card bg-dark m-0" style="min-width:10rem; max-width: 20rem;">
    <div class="card-header">Tag</div>
    <div class="card-body text-white-50">
      <h5 class="card-title">Categorie</h5>
      <p class="card-text">
        <%Tag.all.each do |spectag|%>
        <span class="badge badge-dark"><%=spectag.title%></span>
        <%end%>
      </p>
    </div>
  </div>
  <div class="card bg-light mt-4" style="min-width:10rem; max-width: 20rem;">
    <div class="card-header">Info</div>
    <div class="card-body">
      <h5 class="card-title">Il y'a :</h5>
      <p class="card-text">
       <%=Gossip.all.size%> gossips.
       <br>
       <%=User.all.size%> utilisateurs.

     </p>
   </div>
 </div>

</div>
</div>
</div>

app/views/gossips/new.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh">

  <div class="container-flex w-100 m-0 p-0">
   <% if @gossip.errors.any? %>
   <div class="row justify-content-center m-0 p-0">
    <div class="col-11 col-sm-11 col-lg-8 text-center shadow-sm bg-light rounded p-0">

     <div class="alert alert-danger m-0" role="alert">
      <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% end %>

<div class="row justify-content-center m-0 p-0" style="margin-top: 20px!important; margin-bottom: 20px!important">
  <div class="col-11 col-sm-11 col-lg-8 text-center shadow-sm bg-light rounded pb-4 pt-2" style="margin-top: : 200px">
    <h2 class="h1-responsive font-weight-bold text-center my-4">Gossip</h2>
    <p class="text-center w-responsive mx-auto mb-5">Voici la séction gossip :</p>
    <div class="row m-0 p-0">
      <div class="col-md-12 text-center">
        <ul class="list-unstyled mb-0">
          <li><%= form_tag url_for(action: 'create'), method: "post" do %>

            <div class="row justify-content-center p-0 m-0">
              <div class="col-sm-10 col-lg-4">
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Titre</span>
                  </div>
                  <input type="text" name="title" id="title" class="form-control" placeholder="Titre" aria-label="Titre" aria-describedby="basic-addon1">
                </div>
              </div>
            </div>
            <div class="row justify-content-center p-0 m-0">
              <div class="col-sm-10 col-lg-4">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">Content</span>
                  </div>
                  <textarea name="content" id="content" class="form-control" aria-label="With textarea"></textarea>
                </div>
              </div>
            </div>
            <div class="mt-3">
            </div>


            <div class="row justify-content-center p-0 m-0">
              <div class="col-sm-10 col-lg-4">
                <div class="input-group">
                  <%= select_tag 'tag', options_for_select(Tag.all.collect{ |u| [u.title, u.id] }), multiple: true, :class => "form-control mb-5" %>
                </div>
              </div>
            </div>

            <button type="submit" name="commit" class="btn btn-dark rounded-0">Submit</button>

            <% end %>

app/views/gossips/show.html.erb
<div class="container" style="padding-top: 150px">
  <div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
      <% if GossipTag.where('gossip_id' => params[:id]).any?%>
     <div class="col-12 bg-dark text-center pb-2 pt-1">

      <%GossipTag.where(gossip_id: params[:id]).each do |spectag|%>
      <span class="badge badge-pill badge-light"><%=Tag.find(spectag.tag_id).title%></span>
      <%end%>
    </div>
    <%end%>
    <div class="row shadow-sm bg-white justify-content-between rounded-sm p-3 mb-3 text-dark pr-0 m-0">
     <div class="col-9">
      <span class="font-italic mogos">
        <%=params[:id]%> | <%=Gossip.find(id= params[:id].to_i).user.first_name%> <%=Gossip.find(id= params[:id].to_i).user.last_name%>
      </span>
      <br>
      <%=Gossip.find(id= params[:id].to_i).title%> 
      <br>
      <span class="text-black-50"><%=Gossip.find(id= params[:id].to_i).content%> <span>
      </div>
      <div class="col-auto p-0">
        <div class="row d-flex justify-content-end mr-0  ">
         <%if current_user.has(Gossip.find(id= params[:id].to_i).id)%>       
         <%= form_tag gossip_gossiplike_path(Gossip.find(id= params[:id].to_i).id), method: "delete" do %>
         <button type="submit" name="buto" value="yes" id="fontaws" class="fas fa-heart spec mr-2"></button>
         <%end%>
         <%else%>
         <%= form_tag gossip_gossiplike_index_path(Gossip.find(id= params[:id].to_i).id), method: "post" do %>
         <button type="submit" name="buto" value="yes" id="fontaws" class="far fa-heart spec mr-2"></button>
         <%end%>
         <%end%>
         <a href="<%=edit_gossip_path%>"><i id="fontaws" class="fas fa-pen spec"></i></a> <%= form_tag gossip_path(params[:id]), method: "delete" do %>
         <button type="submit" id="fontaws" class="fas fa-times fa-lg spec ml-2 mb-4"></button>
         <%end%>
       </div>
       <span class="mogos font-italic bg-light p-1 border rounded"><%=Comment.where(:gossip_id =>params[:id].to_i).size%> commentaires</span>
       <span class="mogos font-italic bg-light p-1 border rounded"><%=Like.where(:gossip_id =>params[:id].to_i).size%> likes</span>
     </div>
     <%Comment.where(:gossip_id =>params[:id].to_i).order("created_at ASC").each do |nb|%>
     <div class="col-12 border-top mb-4 mt-4"></div>

     <div class="col-9">
      <span class="font-italic mogos">
        <%=nb.user.first_name%> <%=nb.user.first_name%>
      </span>
      <br>
      <%=nb.content%> 
    </div>
    <div class="col-auto m-0 p-0 text-right">
      <div class="row m-0">
       <%if current_user.hasc(Comment.find(nb.id).id)%>       
       <%= form_tag gossip_comment_commentlike_path(nb.gossip_id,nb.id), method: "delete" do %>
       <button type="submit" name="buto" value="yes" id="fontaws" class="fas fa-heart spec mr-2"></button>
       <%end%>
       <%else%>
       <%= form_tag gossip_comment_commentlike_index_path(nb.gossip_id,nb.id), method: "post" do %>
       <button type="submit" name="buto" value="yes" id="fontaws" class="far fa-heart spec mr-2"></button>
       <%end%>
       <%end%>
       <a href="<%=edit_gossip_comment_path(params[:id],nb.id)%>"><i id="fontaws" class="fas fa-pen spec greycolor"></i></a> <%= form_tag gossip_comment_path(params[:id],nb.id), method: "delete" do %>
       <button type="submit" id="fontaws" class="fas fa-times fa-lg spec ml-2 greycolor"></button>

     </div>
     <span class="mogos font-italic bg-light p-1 border rounded"><%=Like.where(:comment_id =>nb.id).size%> likes</span>
     <%end%>
   </div>
   <%end%>
 </div>


</div>

</div>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
      <div class="row shadow-sm bg-white justify-content-center rounded-sm p-3 mb-3 text-dark pr-0 m-0">

        <%= form_tag gossip_comments_path(params[:id]), method: "post",class: "w-100 " do %>
        <div class="row d-flex justify-content-center">
          <div class="col-12 input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">Commentaire</span>
            </div>
            <textarea name="content" id="content" class="form-control" aria-label="With textarea"></textarea>
          </div>
          <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </div>
        <% end %>
        
        <div class="mt-3">
        </div>


      </div>
    </div>